project_name: demo
subject_code: DemoSubject
epoch_name: auditory_onset
epoch_time_window:
- -1.0
- 2.0
reference_name: noref
load_electrodes: 14-16
analyze_electrodes: '14'
t_window: 100.0
t_step: 100.0
nlambda: 16.0
ncores: .na
trial_num: ~
